version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
      - "5005:5005"
      - "3000:3000"
      - "3003:3003"
    volumes:
      - ./backend:/app                      # your backend code
      - C:\APSRC\DATABASE\:/DATABASE  # 👈 mount external drive folder
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: