export const browserStyles = {
  page: {
    height: "100vh",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    background: "#0f0f0f",
    color: "#eee",
    fontFamily: "'Inter', sans-serif",
    overflow: "hidden",
  },
  header: {
    height: "64px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 24px",
    background: "#1a1a1a",
    borderBottom: "1px solid #333",
    flexShrink: 0,
  },
  pathBar: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "14px",
    color: "#9ca3af",
    fontWeight: "500",
    fontSize: "16px",
  },
  scrollContainer: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
  },
  tableHeader: {
    display: "flex",
    padding: "12px 16px",
    background: "#222",
    borderBottom: "2px solid #333",
    fontWeight: "700",
    fontSize: "16px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: "#888",
  },
  categoryHeader: {
    display: "flex",
    alignItems: "center",
    padding: "10px 16px",
    background: "#1c1c1c",
    borderBottom: "1px solid #333",
    color: "#2f80ed",
    fontSize: "12px",
    fontWeight: "700",
  },
  row: (isChecked) => ({
    display: "flex",
    alignItems: "center",
    padding: "10px 16px",
    borderBottom: "1px solid #252525",
    backgroundColor: isChecked ? "rgba(47, 128, 237, 0.1)" : "transparent",
    transition: "background 0.2s",
  }),
  actionBtn: {
    padding: "6px 12px",
    fontSize: "12px",
    background: "#333",
    color: "#eee",
    border: "1px solid #444",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "600",
  },
  downloadBtn: (active) => ({
    padding: "8px 20px",
    backgroundColor: active ? "#2f80ed" : "#333",
    color: active ? "white" : "#666",
    border: "none",
    borderRadius: "6px",
    fontWeight: "700",
    cursor: active ? "pointer" : "not-allowed",
    transition: "all 0.3s",
  }),
  backBtn: {
    background: "none",
    border: "none",
    color: "#2f80ed",
    cursor: "pointer",
    fontSize: "18px",
    fontWeight: "600",
    padding: 0,
    marginRight: "10px"
  },
  footer: {
    height: "30px",
    flexShrink: 0,
    background: "#0f0f0f",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    color: "#444",
    gap: "10px",
    borderTop: "1px solid #222",
  }
};